---
- name: Install RubyGems
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - ruby
      - rubygems-integration
    state: present
  register: dependencies-capistrano-installation
  tags: dependencies-capistrano